// flow-typed signature: 9d6f2dae814b9200ed737dc3fe928533
// flow-typed version: <<STUB>>/@lugia/jverify_v1.0.6/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@lugia/jverify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@lugia/jverify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@lugia/jverify/interface/jverify.flow' {
  declare module.exports: any;
}

declare module '@lugia/jverify/lib/Const' {
  declare module.exports: any;
}

declare module '@lugia/jverify/lib/cycle' {
  declare module.exports: any;
}

declare module '@lugia/jverify/lib/index' {
  declare module.exports: any;
}

declare module '@lugia/jverify/lib/MockFunction' {
  declare module.exports: any;
}

declare module '@lugia/jverify/lib/MockModule' {
  declare module.exports: any;
}

declare module '@lugia/jverify/lib/VerifyOrder' {
  declare module.exports: any;
}

declare module '@lugia/jverify/lib/VerifyOrderConfig' {
  declare module.exports: any;
}

// Filename aliases
declare module '@lugia/jverify/interface/jverify.flow.js' {
  declare module.exports: $Exports<'@lugia/jverify/interface/jverify.flow'>;
}
declare module '@lugia/jverify/lib/Const.js' {
  declare module.exports: $Exports<'@lugia/jverify/lib/Const'>;
}
declare module '@lugia/jverify/lib/cycle.js' {
  declare module.exports: $Exports<'@lugia/jverify/lib/cycle'>;
}
declare module '@lugia/jverify/lib/index.js' {
  declare module.exports: $Exports<'@lugia/jverify/lib/index'>;
}
declare module '@lugia/jverify/lib/MockFunction.js' {
  declare module.exports: $Exports<'@lugia/jverify/lib/MockFunction'>;
}
declare module '@lugia/jverify/lib/MockModule.js' {
  declare module.exports: $Exports<'@lugia/jverify/lib/MockModule'>;
}
declare module '@lugia/jverify/lib/VerifyOrder.js' {
  declare module.exports: $Exports<'@lugia/jverify/lib/VerifyOrder'>;
}
declare module '@lugia/jverify/lib/VerifyOrderConfig.js' {
  declare module.exports: $Exports<'@lugia/jverify/lib/VerifyOrderConfig'>;
}
