// flow-typed signature: 7c513ebde9b5d149c215ff6a981fd038
// flow-typed version: <<STUB>>/@lugia/mega-scripts_v^1.0.0/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@lugia/mega-scripts'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@lugia/mega-scripts' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@lugia/mega-scripts/bin/mega-scripts' {
  declare module.exports: any;
}

declare module '@lugia/mega-scripts/lib/build' {
  declare module.exports: any;
}

declare module '@lugia/mega-scripts/lib/dev' {
  declare module.exports: any;
}

declare module '@lugia/mega-scripts/lib/index' {
  declare module.exports: any;
}

declare module '@lugia/mega-scripts/lib/test' {
  declare module.exports: any;
}

declare module '@lugia/mega-scripts/lib/utils/babel' {
  declare module.exports: any;
}

declare module '@lugia/mega-scripts/lib/utils/build' {
  declare module.exports: any;
}

declare module '@lugia/mega-scripts/lib/utils/dev' {
  declare module.exports: any;
}

declare module '@lugia/mega-scripts/lib/utils/getEntry' {
  declare module.exports: any;
}

declare module '@lugia/mega-scripts/lib/utils/getPaths' {
  declare module.exports: any;
}

declare module '@lugia/mega-scripts/lib/utils/getWebpackConfig' {
  declare module.exports: any;
}

declare module '@lugia/mega-scripts/lib/utils/mock' {
  declare module.exports: any;
}

declare module '@lugia/mega-scripts/lib/utils/registerBabel' {
  declare module.exports: any;
}

declare module '@lugia/mega-scripts/lib/utils/setPublicPath.tpl' {
  declare module.exports: any;
}

declare module '@lugia/mega-scripts/lib/utils/sheet2json' {
  declare module.exports: any;
}

declare module '@lugia/mega-scripts/lib/utils/winPath' {
  declare module.exports: any;
}

// Filename aliases
declare module '@lugia/mega-scripts/bin/mega-scripts.js' {
  declare module.exports: $Exports<'@lugia/mega-scripts/bin/mega-scripts'>;
}
declare module '@lugia/mega-scripts/lib/build.js' {
  declare module.exports: $Exports<'@lugia/mega-scripts/lib/build'>;
}
declare module '@lugia/mega-scripts/lib/dev.js' {
  declare module.exports: $Exports<'@lugia/mega-scripts/lib/dev'>;
}
declare module '@lugia/mega-scripts/lib/index.js' {
  declare module.exports: $Exports<'@lugia/mega-scripts/lib/index'>;
}
declare module '@lugia/mega-scripts/lib/test.js' {
  declare module.exports: $Exports<'@lugia/mega-scripts/lib/test'>;
}
declare module '@lugia/mega-scripts/lib/utils/babel.js' {
  declare module.exports: $Exports<'@lugia/mega-scripts/lib/utils/babel'>;
}
declare module '@lugia/mega-scripts/lib/utils/build.js' {
  declare module.exports: $Exports<'@lugia/mega-scripts/lib/utils/build'>;
}
declare module '@lugia/mega-scripts/lib/utils/dev.js' {
  declare module.exports: $Exports<'@lugia/mega-scripts/lib/utils/dev'>;
}
declare module '@lugia/mega-scripts/lib/utils/getEntry.js' {
  declare module.exports: $Exports<'@lugia/mega-scripts/lib/utils/getEntry'>;
}
declare module '@lugia/mega-scripts/lib/utils/getPaths.js' {
  declare module.exports: $Exports<'@lugia/mega-scripts/lib/utils/getPaths'>;
}
declare module '@lugia/mega-scripts/lib/utils/getWebpackConfig.js' {
  declare module.exports: $Exports<'@lugia/mega-scripts/lib/utils/getWebpackConfig'>;
}
declare module '@lugia/mega-scripts/lib/utils/mock.js' {
  declare module.exports: $Exports<'@lugia/mega-scripts/lib/utils/mock'>;
}
declare module '@lugia/mega-scripts/lib/utils/registerBabel.js' {
  declare module.exports: $Exports<'@lugia/mega-scripts/lib/utils/registerBabel'>;
}
declare module '@lugia/mega-scripts/lib/utils/setPublicPath.tpl.js' {
  declare module.exports: $Exports<'@lugia/mega-scripts/lib/utils/setPublicPath.tpl'>;
}
declare module '@lugia/mega-scripts/lib/utils/sheet2json.js' {
  declare module.exports: $Exports<'@lugia/mega-scripts/lib/utils/sheet2json'>;
}
declare module '@lugia/mega-scripts/lib/utils/winPath.js' {
  declare module.exports: $Exports<'@lugia/mega-scripts/lib/utils/winPath'>;
}
