// flow-typed signature: 08aba5f61ec37d26f554edaf1347d46d
// flow-typed version: <<STUB>>/@lugia/react-test-utils_v^1.0.0/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@lugia/react-test-utils'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@lugia/react-test-utils' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@lugia/react-test-utils/interface/react-test-utils.flow' {
  declare module.exports: any;
}

// Filename aliases
declare module '@lugia/react-test-utils/index' {
  declare module.exports: $Exports<'@lugia/react-test-utils'>;
}
declare module '@lugia/react-test-utils/index.js' {
  declare module.exports: $Exports<'@lugia/react-test-utils'>;
}
declare module '@lugia/react-test-utils/interface/react-test-utils.flow.js' {
  declare module.exports: $Exports<'@lugia/react-test-utils/interface/react-test-utils.flow'>;
}
