// flow-typed signature: 526d922c18267637da44974be7cea4a2
// flow-typed version: <<STUB>>/@lugia/type-utils_v^1.0.4/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@lugia/type-utils'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@lugia/type-utils' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@lugia/type-utils/interface/type-utils.flow' {
  declare module.exports: any;
}

declare module '@lugia/type-utils/lib/ArrayUtils' {
  declare module.exports: any;
}

declare module '@lugia/type-utils/lib/index' {
  declare module.exports: any;
}

declare module '@lugia/type-utils/lib/NumberUtils' {
  declare module.exports: any;
}

declare module '@lugia/type-utils/lib/ObjectUtils' {
  declare module.exports: any;
}

declare module '@lugia/type-utils/lib/StringUtils' {
  declare module.exports: any;
}

// Filename aliases
declare module '@lugia/type-utils/interface/type-utils.flow.js' {
  declare module.exports: $Exports<'@lugia/type-utils/interface/type-utils.flow'>;
}
declare module '@lugia/type-utils/lib/ArrayUtils.js' {
  declare module.exports: $Exports<'@lugia/type-utils/lib/ArrayUtils'>;
}
declare module '@lugia/type-utils/lib/index.js' {
  declare module.exports: $Exports<'@lugia/type-utils/lib/index'>;
}
declare module '@lugia/type-utils/lib/NumberUtils.js' {
  declare module.exports: $Exports<'@lugia/type-utils/lib/NumberUtils'>;
}
declare module '@lugia/type-utils/lib/ObjectUtils.js' {
  declare module.exports: $Exports<'@lugia/type-utils/lib/ObjectUtils'>;
}
declare module '@lugia/type-utils/lib/StringUtils.js' {
  declare module.exports: $Exports<'@lugia/type-utils/lib/StringUtils'>;
}
