// flow-typed signature: faa7e6300efc0da11add0ee95d20d336
// flow-typed version: <<STUB>>/babel-plugin-react-flow-props-to-prop-types_v^0.15.0/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-react-flow-props-to-prop-types'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-react-flow-props-to-prop-types' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-react-flow-props-to-prop-types/lib/convertTypeToPropTypes' {
  declare module.exports: any;
}

declare module 'babel-plugin-react-flow-props-to-prop-types/lib/error' {
  declare module.exports: any;
}

declare module 'babel-plugin-react-flow-props-to-prop-types/lib/findPropsClassProperty' {
  declare module.exports: any;
}

declare module 'babel-plugin-react-flow-props-to-prop-types/lib/index' {
  declare module.exports: any;
}

declare module 'babel-plugin-react-flow-props-to-prop-types/lib/matchExported' {
  declare module.exports: any;
}

declare module 'babel-plugin-react-flow-props-to-prop-types/lib/types' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-react-flow-props-to-prop-types/lib/convertTypeToPropTypes.js' {
  declare module.exports: $Exports<'babel-plugin-react-flow-props-to-prop-types/lib/convertTypeToPropTypes'>;
}
declare module 'babel-plugin-react-flow-props-to-prop-types/lib/error.js' {
  declare module.exports: $Exports<'babel-plugin-react-flow-props-to-prop-types/lib/error'>;
}
declare module 'babel-plugin-react-flow-props-to-prop-types/lib/findPropsClassProperty.js' {
  declare module.exports: $Exports<'babel-plugin-react-flow-props-to-prop-types/lib/findPropsClassProperty'>;
}
declare module 'babel-plugin-react-flow-props-to-prop-types/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-react-flow-props-to-prop-types/lib/index'>;
}
declare module 'babel-plugin-react-flow-props-to-prop-types/lib/matchExported.js' {
  declare module.exports: $Exports<'babel-plugin-react-flow-props-to-prop-types/lib/matchExported'>;
}
declare module 'babel-plugin-react-flow-props-to-prop-types/lib/types.js' {
  declare module.exports: $Exports<'babel-plugin-react-flow-props-to-prop-types/lib/types'>;
}
