// flow-typed signature: 399fceed76b3e435ce9aab31a9c6fd97
// flow-typed version: <<STUB>>/classnames_v2.2.5/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'classnames'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'classnames' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'classnames/bind' {
  declare module.exports: any;
}

declare module 'classnames/dedupe' {
  declare module.exports: any;
}

// Filename aliases
declare module 'classnames/bind.js' {
  declare module.exports: $Exports<'classnames/bind'>;
}
declare module 'classnames/dedupe.js' {
  declare module.exports: $Exports<'classnames/dedupe'>;
}
declare module 'classnames/index' {
  declare module.exports: $Exports<'classnames'>;
}
declare module 'classnames/index.js' {
  declare module.exports: $Exports<'classnames'>;
}
