// flow-typed signature: 753adc1485131b08f7ba3bf82b7c9a1f
// flow-typed version: <<STUB>>/css-animation_v^1.4.1/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'css-animation'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'css-animation' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'css-animation/es/Event' {
  declare module.exports: any;
}

declare module 'css-animation/es/index' {
  declare module.exports: any;
}

declare module 'css-animation/lib/Event' {
  declare module.exports: any;
}

declare module 'css-animation/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'css-animation/es/Event.js' {
  declare module.exports: $Exports<'css-animation/es/Event'>;
}
declare module 'css-animation/es/index.js' {
  declare module.exports: $Exports<'css-animation/es/index'>;
}
declare module 'css-animation/lib/Event.js' {
  declare module.exports: $Exports<'css-animation/lib/Event'>;
}
declare module 'css-animation/lib/index.js' {
  declare module.exports: $Exports<'css-animation/lib/index'>;
}
