// flow-typed signature: 88529bedc0ef475790b832942d05646c
// flow-typed version: <<STUB>>/dragdealer_v0.9.9/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dragdealer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'dragdealer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'dragdealer/Gruntfile' {
  declare module.exports: any;
}

declare module 'dragdealer/spec/apiSpec' {
  declare module.exports: any;
}

declare module 'dragdealer/spec/browser-runner' {
  declare module.exports: any;
}

declare module 'dragdealer/spec/callbacksSpec' {
  declare module.exports: any;
}

declare module 'dragdealer/spec/draggingSpec' {
  declare module.exports: any;
}

declare module 'dragdealer/spec/eventsSpec' {
  declare module.exports: any;
}

declare module 'dragdealer/spec/helpers' {
  declare module.exports: any;
}

declare module 'dragdealer/spec/matchers' {
  declare module.exports: any;
}

declare module 'dragdealer/spec/optionsSpec' {
  declare module.exports: any;
}

declare module 'dragdealer/spec/phantomjs-setup' {
  declare module.exports: any;
}

declare module 'dragdealer/spec/resizingSpec' {
  declare module.exports: any;
}

declare module 'dragdealer/spec/setup' {
  declare module.exports: any;
}

declare module 'dragdealer/spec/touchDraggingSpec' {
  declare module.exports: any;
}

declare module 'dragdealer/src/dragdealer' {
  declare module.exports: any;
}

// Filename aliases
declare module 'dragdealer/Gruntfile.js' {
  declare module.exports: $Exports<'dragdealer/Gruntfile'>;
}
declare module 'dragdealer/spec/apiSpec.js' {
  declare module.exports: $Exports<'dragdealer/spec/apiSpec'>;
}
declare module 'dragdealer/spec/browser-runner.js' {
  declare module.exports: $Exports<'dragdealer/spec/browser-runner'>;
}
declare module 'dragdealer/spec/callbacksSpec.js' {
  declare module.exports: $Exports<'dragdealer/spec/callbacksSpec'>;
}
declare module 'dragdealer/spec/draggingSpec.js' {
  declare module.exports: $Exports<'dragdealer/spec/draggingSpec'>;
}
declare module 'dragdealer/spec/eventsSpec.js' {
  declare module.exports: $Exports<'dragdealer/spec/eventsSpec'>;
}
declare module 'dragdealer/spec/helpers.js' {
  declare module.exports: $Exports<'dragdealer/spec/helpers'>;
}
declare module 'dragdealer/spec/matchers.js' {
  declare module.exports: $Exports<'dragdealer/spec/matchers'>;
}
declare module 'dragdealer/spec/optionsSpec.js' {
  declare module.exports: $Exports<'dragdealer/spec/optionsSpec'>;
}
declare module 'dragdealer/spec/phantomjs-setup.js' {
  declare module.exports: $Exports<'dragdealer/spec/phantomjs-setup'>;
}
declare module 'dragdealer/spec/resizingSpec.js' {
  declare module.exports: $Exports<'dragdealer/spec/resizingSpec'>;
}
declare module 'dragdealer/spec/setup.js' {
  declare module.exports: $Exports<'dragdealer/spec/setup'>;
}
declare module 'dragdealer/spec/touchDraggingSpec.js' {
  declare module.exports: $Exports<'dragdealer/spec/touchDraggingSpec'>;
}
declare module 'dragdealer/src/dragdealer.js' {
  declare module.exports: $Exports<'dragdealer/src/dragdealer'>;
}
