// flow-typed signature: bf3b7856d9564bbde7d2db7db10c644a
// flow-typed version: <<STUB>>/enquire.js_v^2.1.6/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'enquire.js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'enquire.js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'enquire.js/dist/enquire' {
  declare module.exports: any;
}

declare module 'enquire.js/dist/enquire.min' {
  declare module.exports: any;
}

declare module 'enquire.js/src/index' {
  declare module.exports: any;
}

declare module 'enquire.js/src/MediaQuery' {
  declare module.exports: any;
}

declare module 'enquire.js/src/MediaQueryDispatch' {
  declare module.exports: any;
}

declare module 'enquire.js/src/QueryHandler' {
  declare module.exports: any;
}

declare module 'enquire.js/src/Util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'enquire.js/dist/enquire.js' {
  declare module.exports: $Exports<'enquire.js/dist/enquire'>;
}
declare module 'enquire.js/dist/enquire.min.js' {
  declare module.exports: $Exports<'enquire.js/dist/enquire.min'>;
}
declare module 'enquire.js/src/index.js' {
  declare module.exports: $Exports<'enquire.js/src/index'>;
}
declare module 'enquire.js/src/MediaQuery.js' {
  declare module.exports: $Exports<'enquire.js/src/MediaQuery'>;
}
declare module 'enquire.js/src/MediaQueryDispatch.js' {
  declare module.exports: $Exports<'enquire.js/src/MediaQueryDispatch'>;
}
declare module 'enquire.js/src/QueryHandler.js' {
  declare module.exports: $Exports<'enquire.js/src/QueryHandler'>;
}
declare module 'enquire.js/src/Util.js' {
  declare module.exports: $Exports<'enquire.js/src/Util'>;
}
