// flow-typed signature: 843b991d3aebebfb50374586a6b8b379
// flow-typed version: <<STUB>>/enquire.js_v^2.1.6/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'enquire.js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'enquire.js' {
  declare module.exports: any;
}
