// flow-typed signature: 9f564e522882984758078c49b49a2bdc
// flow-typed version: <<STUB>>/gulp-newer_v1/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-newer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-newer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gulp-newer/spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gulp-newer/index' {
  declare module.exports: $Exports<'gulp-newer'>;
}
declare module 'gulp-newer/index.js' {
  declare module.exports: $Exports<'gulp-newer'>;
}
declare module 'gulp-newer/spec.js' {
  declare module.exports: $Exports<'gulp-newer/spec'>;
}
