// flow-typed signature: 29d49a1bda58d95139d40467cc4fc6f4
// flow-typed version: <<STUB>>/gulp-changed_v3/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-changed'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-changed' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'gulp-changed/index' {
  declare module.exports: $Exports<'gulp-changed'>;
}
declare module 'gulp-changed/index.js' {
  declare module.exports: $Exports<'gulp-changed'>;
}
