// flow-typed signature: e5e3b9507f66c7a6057f82e37f8da213
// flow-typed version: <<STUB>>/rc-align_v2.4.3/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rc-align'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rc-align' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rc-align/es/Align' {
  declare module.exports: any;
}

declare module 'rc-align/es/index' {
  declare module.exports: any;
}

declare module 'rc-align/es/util' {
  declare module.exports: any;
}

declare module 'rc-align/lib/Align' {
  declare module.exports: any;
}

declare module 'rc-align/lib/index' {
  declare module.exports: any;
}

declare module 'rc-align/lib/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rc-align/es/Align.js' {
  declare module.exports: $Exports<'rc-align/es/Align'>;
}
declare module 'rc-align/es/index.js' {
  declare module.exports: $Exports<'rc-align/es/index'>;
}
declare module 'rc-align/es/util.js' {
  declare module.exports: $Exports<'rc-align/es/util'>;
}
declare module 'rc-align/lib/Align.js' {
  declare module.exports: $Exports<'rc-align/lib/Align'>;
}
declare module 'rc-align/lib/index.js' {
  declare module.exports: $Exports<'rc-align/lib/index'>;
}
declare module 'rc-align/lib/util.js' {
  declare module.exports: $Exports<'rc-align/lib/util'>;
}
