// flow-typed signature: 16239acc492815392a1eba046217a7db
// flow-typed version: <<STUB>>/rc-align_v2.x/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rc-align'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rc-align' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rc-align/lib/Align' {
  declare module.exports: any;
}

declare module 'rc-align/lib/index' {
  declare module.exports: any;
}

declare module 'rc-align/lib/isWindow' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rc-align/lib/Align.js' {
  declare module.exports: $Exports<'rc-align/lib/Align'>;
}
declare module 'rc-align/lib/index.js' {
  declare module.exports: $Exports<'rc-align/lib/index'>;
}
declare module 'rc-align/lib/isWindow.js' {
  declare module.exports: $Exports<'rc-align/lib/isWindow'>;
}
