// flow-typed signature: a44b69a76a94ede12e895a66cc54fb2c
// flow-typed version: <<STUB>>/rc-table_v6.4.0/flow_v0.87.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rc-table'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rc-table' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rc-table/assets/index.css' {
  declare module.exports: any;
}
declare module 'rc-table/dist/rc-table' {
  declare module.exports: any;
}

declare module 'rc-table/dist/rc-table.min' {
  declare module.exports: any;
}

declare module 'rc-table/es/BaseTable' {
  declare module.exports: any;
}

declare module 'rc-table/es/BodyTable' {
  declare module.exports: any;
}

declare module 'rc-table/es/ColGroup' {
  declare module.exports: any;
}

declare module 'rc-table/es/Column' {
  declare module.exports: any;
}

declare module 'rc-table/es/ColumnGroup' {
  declare module.exports: any;
}

declare module 'rc-table/es/ColumnManager' {
  declare module.exports: any;
}

declare module 'rc-table/es/ExpandableRow' {
  declare module.exports: any;
}

declare module 'rc-table/es/ExpandableTable' {
  declare module.exports: any;
}

declare module 'rc-table/es/ExpandIcon' {
  declare module.exports: any;
}

declare module 'rc-table/es/HeadTable' {
  declare module.exports: any;
}

declare module 'rc-table/es/index' {
  declare module.exports: any;
}

declare module 'rc-table/es/Table' {
  declare module.exports: any;
}

declare module 'rc-table/es/TableCell' {
  declare module.exports: any;
}

declare module 'rc-table/es/TableHeader' {
  declare module.exports: any;
}

declare module 'rc-table/es/TableHeaderRow' {
  declare module.exports: any;
}

declare module 'rc-table/es/TableRow' {
  declare module.exports: any;
}

declare module 'rc-table/es/utils' {
  declare module.exports: any;
}

declare module 'rc-table/lib/BaseTable' {
  declare module.exports: any;
}

declare module 'rc-table/lib/BodyTable' {
  declare module.exports: any;
}

declare module 'rc-table/lib/ColGroup' {
  declare module.exports: any;
}

declare module 'rc-table/lib/Column' {
  declare module.exports: any;
}

declare module 'rc-table/lib/ColumnGroup' {
  declare module.exports: any;
}

declare module 'rc-table/lib/ColumnManager' {
  declare module.exports: any;
}

declare module 'rc-table/lib/ExpandableRow' {
  declare module.exports: any;
}

declare module 'rc-table/lib/ExpandableTable' {
  declare module.exports: any;
}

declare module 'rc-table/lib/ExpandIcon' {
  declare module.exports: any;
}

declare module 'rc-table/lib/HeadTable' {
  declare module.exports: any;
}

declare module 'rc-table/lib/index' {
  declare module.exports: any;
}

declare module 'rc-table/lib/Table' {
  declare module.exports: any;
}

declare module 'rc-table/lib/TableCell' {
  declare module.exports: any;
}

declare module 'rc-table/lib/TableHeader' {
  declare module.exports: any;
}

declare module 'rc-table/lib/TableHeaderRow' {
  declare module.exports: any;
}

declare module 'rc-table/lib/TableRow' {
  declare module.exports: any;
}

declare module 'rc-table/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rc-table/dist/rc-table.js' {
  declare module.exports: $Exports<'rc-table/dist/rc-table'>;
}
declare module 'rc-table/dist/rc-table.min.js' {
  declare module.exports: $Exports<'rc-table/dist/rc-table.min'>;
}
declare module 'rc-table/es/BaseTable.js' {
  declare module.exports: $Exports<'rc-table/es/BaseTable'>;
}
declare module 'rc-table/es/BodyTable.js' {
  declare module.exports: $Exports<'rc-table/es/BodyTable'>;
}
declare module 'rc-table/es/ColGroup.js' {
  declare module.exports: $Exports<'rc-table/es/ColGroup'>;
}
declare module 'rc-table/es/Column.js' {
  declare module.exports: $Exports<'rc-table/es/Column'>;
}
declare module 'rc-table/es/ColumnGroup.js' {
  declare module.exports: $Exports<'rc-table/es/ColumnGroup'>;
}
declare module 'rc-table/es/ColumnManager.js' {
  declare module.exports: $Exports<'rc-table/es/ColumnManager'>;
}
declare module 'rc-table/es/ExpandableRow.js' {
  declare module.exports: $Exports<'rc-table/es/ExpandableRow'>;
}
declare module 'rc-table/es/ExpandableTable.js' {
  declare module.exports: $Exports<'rc-table/es/ExpandableTable'>;
}
declare module 'rc-table/es/ExpandIcon.js' {
  declare module.exports: $Exports<'rc-table/es/ExpandIcon'>;
}
declare module 'rc-table/es/HeadTable.js' {
  declare module.exports: $Exports<'rc-table/es/HeadTable'>;
}
declare module 'rc-table/es/index.js' {
  declare module.exports: $Exports<'rc-table/es/index'>;
}
declare module 'rc-table/es/Table.js' {
  declare module.exports: $Exports<'rc-table/es/Table'>;
}
declare module 'rc-table/es/TableCell.js' {
  declare module.exports: $Exports<'rc-table/es/TableCell'>;
}
declare module 'rc-table/es/TableHeader.js' {
  declare module.exports: $Exports<'rc-table/es/TableHeader'>;
}
declare module 'rc-table/es/TableHeaderRow.js' {
  declare module.exports: $Exports<'rc-table/es/TableHeaderRow'>;
}
declare module 'rc-table/es/TableRow.js' {
  declare module.exports: $Exports<'rc-table/es/TableRow'>;
}
declare module 'rc-table/es/utils.js' {
  declare module.exports: $Exports<'rc-table/es/utils'>;
}
declare module 'rc-table/lib/BaseTable.js' {
  declare module.exports: $Exports<'rc-table/lib/BaseTable'>;
}
declare module 'rc-table/lib/BodyTable.js' {
  declare module.exports: $Exports<'rc-table/lib/BodyTable'>;
}
declare module 'rc-table/lib/ColGroup.js' {
  declare module.exports: $Exports<'rc-table/lib/ColGroup'>;
}
declare module 'rc-table/lib/Column.js' {
  declare module.exports: $Exports<'rc-table/lib/Column'>;
}
declare module 'rc-table/lib/ColumnGroup.js' {
  declare module.exports: $Exports<'rc-table/lib/ColumnGroup'>;
}
declare module 'rc-table/lib/ColumnManager.js' {
  declare module.exports: $Exports<'rc-table/lib/ColumnManager'>;
}
declare module 'rc-table/lib/ExpandableRow.js' {
  declare module.exports: $Exports<'rc-table/lib/ExpandableRow'>;
}
declare module 'rc-table/lib/ExpandableTable.js' {
  declare module.exports: $Exports<'rc-table/lib/ExpandableTable'>;
}
declare module 'rc-table/lib/ExpandIcon.js' {
  declare module.exports: $Exports<'rc-table/lib/ExpandIcon'>;
}
declare module 'rc-table/lib/HeadTable.js' {
  declare module.exports: $Exports<'rc-table/lib/HeadTable'>;
}
declare module 'rc-table/lib/index.js' {
  declare module.exports: $Exports<'rc-table/lib/index'>;
}
declare module 'rc-table/lib/Table.js' {
  declare module.exports: $Exports<'rc-table/lib/Table'>;
}
declare module 'rc-table/lib/TableCell.js' {
  declare module.exports: $Exports<'rc-table/lib/TableCell'>;
}
declare module 'rc-table/lib/TableHeader.js' {
  declare module.exports: $Exports<'rc-table/lib/TableHeader'>;
}
declare module 'rc-table/lib/TableHeaderRow.js' {
  declare module.exports: $Exports<'rc-table/lib/TableHeaderRow'>;
}
declare module 'rc-table/lib/TableRow.js' {
  declare module.exports: $Exports<'rc-table/lib/TableRow'>;
}
declare module 'rc-table/lib/utils.js' {
  declare module.exports: $Exports<'rc-table/lib/utils'>;
}
