// flow-typed signature: 561ca984275d031d6fb98ecf19cf6b34
// flow-typed version: <<STUB>>/rc-tree_v1.7.4/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rc-tree'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rc-tree' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rc-tree/es/index' {
  declare module.exports: any;
}

declare module 'rc-tree/es/Tree' {
  declare module.exports: any;
}

declare module 'rc-tree/es/TreeNode' {
  declare module.exports: any;
}

declare module 'rc-tree/es/util' {
  declare module.exports: any;
}

declare module 'rc-tree/lib/index' {
  declare module.exports: any;
}

declare module 'rc-tree/lib/Tree' {
  declare module.exports: any;
}

declare module 'rc-tree/lib/TreeNode' {
  declare module.exports: any;
}

declare module 'rc-tree/lib/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rc-tree/es/index.js' {
  declare module.exports: $Exports<'rc-tree/es/index'>;
}
declare module 'rc-tree/es/Tree.js' {
  declare module.exports: $Exports<'rc-tree/es/Tree'>;
}
declare module 'rc-tree/es/TreeNode.js' {
  declare module.exports: $Exports<'rc-tree/es/TreeNode'>;
}
declare module 'rc-tree/es/util.js' {
  declare module.exports: $Exports<'rc-tree/es/util'>;
}
declare module 'rc-tree/lib/index.js' {
  declare module.exports: $Exports<'rc-tree/lib/index'>;
}
declare module 'rc-tree/lib/Tree.js' {
  declare module.exports: $Exports<'rc-tree/lib/Tree'>;
}
declare module 'rc-tree/lib/TreeNode.js' {
  declare module.exports: $Exports<'rc-tree/lib/TreeNode'>;
}
declare module 'rc-tree/lib/util.js' {
  declare module.exports: $Exports<'rc-tree/lib/util'>;
}
