// flow-typed signature: 9a37d142952c2a92ab637db3ab88e3d9
// flow-typed version: <<STUB>>/vx-mock_v^0.1.7/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vx-mock'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vx-mock' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vx-mock/interface/vx-mock.flow' {
  declare module.exports: any;
}

declare module 'vx-mock/lib/Const' {
  declare module.exports: any;
}

declare module 'vx-mock/lib/index' {
  declare module.exports: any;
}

declare module 'vx-mock/lib/MockFunction' {
  declare module.exports: any;
}

declare module 'vx-mock/lib/MockModule' {
  declare module.exports: any;
}

declare module 'vx-mock/lib/VerifyOrder' {
  declare module.exports: any;
}

declare module 'vx-mock/lib/VerifyOrderConfig' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vx-mock/interface/vx-mock.flow.js' {
  declare module.exports: $Exports<'vx-mock/interface/vx-mock.flow'>;
}
declare module 'vx-mock/lib/Const.js' {
  declare module.exports: $Exports<'vx-mock/lib/Const'>;
}
declare module 'vx-mock/lib/index.js' {
  declare module.exports: $Exports<'vx-mock/lib/index'>;
}
declare module 'vx-mock/lib/MockFunction.js' {
  declare module.exports: $Exports<'vx-mock/lib/MockFunction'>;
}
declare module 'vx-mock/lib/MockModule.js' {
  declare module.exports: $Exports<'vx-mock/lib/MockModule'>;
}
declare module 'vx-mock/lib/VerifyOrder.js' {
  declare module.exports: $Exports<'vx-mock/lib/VerifyOrder'>;
}
declare module 'vx-mock/lib/VerifyOrderConfig.js' {
  declare module.exports: $Exports<'vx-mock/lib/VerifyOrderConfig'>;
}
