export const mockVirtualColumns = [
  {
    title: '日期',
    dataIndex: 'firstC',
    key: 'firstC',
    align: 'left',
    ellipsis: true,
    width: 142,
    sortType: 'number',
    titleAlign: 'center',
  },
  {
    title: '净值',
    dataIndex: 'secondC',
    key: 'secondC',
    align: 'left',
    ellipsis: true,
    width: 168,
    sortType: 'number',
    titleAlign: 'center',
  },
  {
    title: '日收益',
    dataIndex: 'thirdC',
    key: 'thirdC',
    align: 'left',
    ellipsis: true,
    width: 88,
    sortType: 'number',
    titleAlign: 'center',
  },
  {
    title: '日收益率(%)',
    dataIndex: 'fourthC',
    key: 'fourthC',
    align: 'left',
    ellipsis: true,
    width: 128,
    sortType: 'number',
    titleAlign: 'center',
  },
  {
    title: '净值',
    dataIndex: 'fifthC',
    key: 'fifthC',
    align: 'left',
    ellipsis: true,
    width: 168,
    sortType: 'number',
    titleAlign: 'center',
  },
];

export default [
  {
    title: '日期',
    dataIndex: 'bizDate',
    key: 'bizDate',
    align: 'left',
    ellipsis: true,
    width: 142,
    sortType: 'number',
    titleAlign: 'center',
  },
  {
    title: '净值',
    dataIndex: 'domeEntrustedStockNetValue',
    key: 'domeEntrustedStockNetValue',
    align: 'right',
    ellipsis: true,
    width: 168,
    sortType: 'number',
    titleAlign: 'center',
  },
  {
    title: '日收益',
    dataIndex: 'domeEntrustedStockIncome',
    key: 'domeEntrustedStockIncome',
    align: 'right',
    ellipsis: true,
    width: 88,
    sortType: 'number',
    titleAlign: 'center',
    sorter: (a, b) => {
      return a.domeEntrustedStockIncome - b.domeEntrustedStockIncome;
    },
  },
  {
    title: '日收益率(%)',
    dataIndex: 'domeEntrustedStockYieldRate',
    key: 'domeEntrustedStockYieldRate',
    align: 'right',
    ellipsis: true,
    width: 128,
    sortType: 'number',
    titleAlign: 'center',
    sorter: (a, b) => {
      return a.domeEntrustedStockYieldRate - b.domeEntrustedStockYieldRate;
    },
  },
  {
    title: '净值',
    dataIndex: 'domeTransferredStockNetValue',
    key: 'domeTransferredStockNetValue',
    align: 'right',
    ellipsis: true,
    width: 168,
    sortType: 'number',
    titleAlign: 'center',
  },
  {
    title: '日收益',
    dataIndex: 'domeTransferredStockIncome',
    key: 'domeTransferredStockIncome',
    align: 'right',
    ellipsis: true,
    width: 88,
    sortType: 'number',
    titleAlign: 'center',
  },
  {
    title: '日收益率(%)',
    dataIndex: 'domeTransferredStockYieldRate',
    key: 'domeTransferredStockYieldRate',
    align: 'right',
    ellipsis: true,
    width: 128,
    sortType: 'number',
    titleAlign: 'center',
  },
  {
    title: '净值',
    dataIndex: 'domeProprietaryStockNetValue',
    key: 'domeProprietaryStockNetValue',
    align: 'right',
    ellipsis: true,
    width: 168,
    sortType: 'number',
    titleAlign: 'center',
  },
  {
    title: '日收益',
    dataIndex: 'domeProprietaryStockIncome',
    key: 'domeProprietaryStockIncome',
    align: 'right',
    ellipsis: true,
    width: 88,
    sortType: 'number',
    titleAlign: 'center',
  },
  {
    title: '日收益率(%)',
    dataIndex: 'domeProprietaryStockYieldRate',
    key: 'domeProprietaryStockYieldRate',
    align: 'right',
    ellipsis: true,
    width: 128,
    sortType: 'number',
    titleAlign: 'center',
  },
  {
    title: '净值',
    dataIndex: 'overseasEntrustedStockNetValue',
    key: 'overseasEntrustedStockNetValue',
    align: 'right',
    ellipsis: true,
    width: 168,
    sortType: 'number',
    titleAlign: 'center',
  },
  {
    title: '日收益',
    dataIndex: 'overseasEntrustedStockIncome',
    key: 'overseasEntrustedStockIncome',
    align: 'right',
    ellipsis: true,
    width: 88,
    sortType: 'number',
    titleAlign: 'center',
  },
  {
    title: '日收益率(%)',
    dataIndex: 'overseasEntrustedStockYieldRate',
    key: 'overseasEntrustedStockYieldRate',
    align: 'right',
    ellipsis: true,
    width: 128,
    sortType: 'number',
    titleAlign: 'center',
  },
  {
    title: '净值',
    dataIndex: 'overseasPlacementNetValue',
    key: 'overseasPlacementNetValue',
    align: 'right',
    ellipsis: true,
    width: 136,
    sortType: 'number',
    titleAlign: 'center',
  },
  {
    title: '日收益',
    dataIndex: 'overseasPlacementIncome',
    key: 'overseasPlacementIncome',
    align: 'right',
    ellipsis: true,
    width: 88,
    sortType: 'number',
    titleAlign: 'center',
  },
  {
    title: '日收益率(%)',
    dataIndex: 'overseasPlacementYieldRate',
    key: 'overseasPlacementYieldRate',
    align: 'right',
    ellipsis: true,
    width: 128,
    sortType: 'number',
    titleAlign: 'center',
  },
  {
    title: '净值',
    dataIndex: 'overseasTransferredStockNetValue',
    key: 'overseasTransferredStockNetValue',
    align: 'right',
    ellipsis: true,
    width: 168,
    sortType: 'number',
    titleAlign: 'center',
  },
  {
    title: '日收益',
    dataIndex: 'overseasTransferredStockIncome',
    key: 'overseasTransferredStockIncome',
    align: 'right',
    ellipsis: true,
    width: 88,
    sortType: 'number',
    titleAlign: 'center',
  },
  {
    title: '日收益率(%)',
    dataIndex: 'overseasTransferredStockYieldRate',
    key: 'overseasTransferredStockYieldRate',
    align: 'right',
    ellipsis: true,
    width: 128,
    sortType: 'number',
    titleAlign: 'center',
  },
  {
    title: '净值',
    dataIndex: 'hkStockNetValue',
    key: 'hkStockNetValue',
    align: 'right',
    ellipsis: true,
    width: 152,
    sortType: 'number',
    titleAlign: 'center',
  },
  {
    title: '日收益',
    dataIndex: 'hkStockIncome',
    key: 'hkStockIncome',
    align: 'right',
    ellipsis: true,
    width: 88,
    sortType: 'number',
    titleAlign: 'center',
  },
  {
    title: '日收益率(%)',
    dataIndex: 'hkStockYieldRate',
    key: 'hkStockYieldRate',
    align: 'right',
    ellipsis: true,
    width: 128,
    sortType: 'number',
    titleAlign: 'center',
  },
  {
    title: '净值',
    dataIndex: 'timeDepositNetValue',
    key: 'timeDepositNetValue',
    align: 'right',
    ellipsis: true,
    width: 152,
    sortType: 'number',
    titleAlign: 'center',
  },
  {
    title: '日收益',
    dataIndex: 'timeDepositIncome',
    key: 'timeDepositIncome',
    align: 'right',
    ellipsis: true,
    width: 88,
    sortType: 'number',
    titleAlign: 'center',
  },
  {
    title: '日收益率(%)',
    dataIndex: 'timeDepositYieldRate',
    key: 'timeDepositYieldRate',
    align: 'right',
    ellipsis: true,
    width: 128,
    sortType: 'number',
    titleAlign: 'center',
  },
  {
    title: '净值',
    dataIndex: 'agreementDepositNetValue',
    key: 'agreementDepositNetValue',
    align: 'right',
    ellipsis: true,
    width: 136,
    sortType: 'number',
    titleAlign: 'center',
  },
  {
    title: '日收益',
    dataIndex: 'agreementDepositIncome',
    key: 'agreementDepositIncome',
    align: 'right',
    ellipsis: true,
    width: 88,
    sortType: 'number',
    titleAlign: 'center',
  },
  {
    title: '日收益率(%)',
    dataIndex: 'agreementDepositYieldRate',
    key: 'agreementDepositYieldRate',
    align: 'right',
    ellipsis: true,
    width: 128,
    sortType: 'number',
    titleAlign: 'center',
  },
  {
    title: '净值',
    dataIndex: 'overYearDepositNetValue',
    key: 'overYearDepositNetValue',
    align: 'right',
    ellipsis: true,
    width: 216,
    sortType: 'number',
    titleAlign: 'center',
  },
  {
    title: '日收益',
    dataIndex: 'overYearDepositIncome',
    key: 'overYearDepositIncome',
    align: 'right',
    ellipsis: true,
    width: 88,
    sortType: 'number',
    titleAlign: 'center',
  },
  {
    title: '日收益率(%)',
    dataIndex: 'overYearDepositYieldRate',
    key: 'overYearDepositYieldRate',
    align: 'right',
    ellipsis: true,
    width: 128,
    sortType: 'number',
    titleAlign: 'center',
  },
  {
    title: '净值',
    dataIndex: 'domeEntrustedBondsNetValue',
    key: 'domeEntrustedBondsNetValue',
    align: 'right',
    ellipsis: true,
    width: 168,
    sortType: 'number',
    titleAlign: 'center',
  },
  {
    title: '日收益',
    dataIndex: 'domeEntrustedBondsIncome',
    key: 'domeEntrustedBondsIncome',
    align: 'right',
    ellipsis: true,
    width: 88,
    sortType: 'number',
    titleAlign: 'center',
  },
  {
    title: '日收益率(%)',
    dataIndex: 'domeEntrustedBondsYieldRate',
    key: 'domeEntrustedBondsYieldRate',
    align: 'right',
    ellipsis: true,
    width: 128,
    sortType: 'number',
    titleAlign: 'center',
  },
  {
    title: '净值',
    dataIndex: 'tradingBondsNetValue',
    key: 'tradingBondsNetValue',
    align: 'right',
    ellipsis: true,
    width: 152,
    sortType: 'number',
    titleAlign: 'center',
  },
  {
    title: '日收益',
    dataIndex: 'tradingBondsIncome',
    key: 'tradingBondsIncome',
    align: 'right',
    ellipsis: true,
    width: 88,
    sortType: 'number',
    titleAlign: 'center',
  },
  {
    title: '日收益率(%)',
    dataIndex: 'tradingBondsYieldRate',
    key: 'tradingBondsYieldRate',
    align: 'right',
    ellipsis: true,
    width: 128,
    sortType: 'number',
    titleAlign: 'center',
  },
  {
    title: '净值',
    dataIndex: 'maturityBondsNetValue',
    key: 'maturityBondsNetValue',
    align: 'right',
    ellipsis: true,
    width: 200,
    sortType: 'number',
    titleAlign: 'center',
  },
  {
    title: '日收益',
    dataIndex: 'maturityBondsIncome',
    key: 'maturityBondsIncome',
    align: 'right',
    ellipsis: true,
    width: 88,
    sortType: 'number',
    titleAlign: 'center',
  },
  {
    title: '日收益率(%)',
    dataIndex: 'maturityBondsYieldRate',
    key: 'maturityBondsYieldRate',
    align: 'right',
    ellipsis: true,
    width: 128,
    sortType: 'number',
    titleAlign: 'center',
  },
  {
    title: '券净值',
    dataIndex: 'overEntrustedBondsNetValue',
    key: 'overEntrustedBondsNetValue',
    align: 'right',
    ellipsis: true,
    width: 168,
    sortType: 'number',
    titleAlign: 'center',
  },
  {
    title: '日收益',
    dataIndex: 'overEntrustedBondsIncome',
    key: 'overEntrustedBondsIncome',
    align: 'right',
    ellipsis: true,
    width: 88,
    sortType: 'number',
    titleAlign: 'center',
  },
  {
    title: '日收益率(%)',
    dataIndex: 'overEntrustedBondsYieldRate',
    key: 'overEntrustedBondsYieldRate',
    align: 'right',
    ellipsis: true,
    width: 128,
    sortType: 'number',
    titleAlign: 'center',
  },
  {
    title: '净值',
    dataIndex: 'trustNetValue',
    key: 'trustNetValue',
    align: 'right',
    ellipsis: true,
    width: 104,
    sortType: 'number',
    titleAlign: 'center',
  },
  {
    title: '日收益',
    dataIndex: 'trustIncome',
    key: 'trustIncome',
    align: 'right',
    ellipsis: true,
    width: 88,
    sortType: 'number',
    titleAlign: 'center',
  },
  {
    title: '日收益率(%)',
    dataIndex: 'trustYieldRate',
    key: 'trustYieldRate',
    align: 'right',
    ellipsis: true,
    width: 128,
    sortType: 'number',
    titleAlign: 'center',
  },
  {
    title: '优先值',
    dataIndex: 'preferredStockNetValue',
    key: 'preferredStockNetValue',
    align: 'right',
    ellipsis: true,
    width: 120,
    sortType: 'number',
    titleAlign: 'center',
  },
  {
    title: '日收益',
    dataIndex: 'preferredStockIncome',
    key: 'preferredStockIncome',
    align: 'right',
    ellipsis: true,
    width: 88,
    sortType: 'number',
    titleAlign: 'center',
  },
  {
    title: '日收益率(%)',
    dataIndex: 'preferredStockYieldRate',
    key: 'preferredStockYieldRate',
    align: 'right',
    ellipsis: true,
    width: 128,
    sortType: 'number',
    titleAlign: 'center',
  },
  {
    title: '资产值',
    dataIndex: 'assetBackedBondNetValue',
    key: 'assetBackedBondNetValue',
    align: 'right',
    ellipsis: true,
    width: 168,
    sortType: 'number',
    titleAlign: 'center',
  },
  {
    title: '日收益',
    dataIndex: 'assetBackedBondIncome',
    key: 'assetBackedBondIncome',
    align: 'right',
    ellipsis: true,
    width: 88,
    sortType: 'number',
    titleAlign: 'center',
  },
  {
    title: '日收益率(%)',
    dataIndex: 'assetBackedBondYieldRate',
    key: 'assetBackedBondYieldRate',
    align: 'right',
    ellipsis: true,
    width: 128,
    sortType: 'number',
    titleAlign: 'center',
  },
  {
    title: '其他值',
    dataIndex: 'otherInvestmentsNetValue',
    key: 'otherInvestmentsNetValue',
    align: 'right',
    ellipsis: true,
    width: 136,
    sortType: 'number',
    titleAlign: 'center',
  },
  {
    title: '日收益',
    dataIndex: 'otherInvestmentsIncome',
    key: 'otherInvestmentsIncome',
    align: 'right',
    ellipsis: true,
    width: 88,
    sortType: 'number',
    titleAlign: 'center',
  },
  {
    title: '日收益率(%)',
    dataIndex: 'otherInvestmentsYieldRate',
    key: 'otherInvestmentsYieldRate',
    align: 'right',
    ellipsis: true,
    width: 128,
    sortType: 'number',
    titleAlign: 'center',
  },
  {
    title: '直接值',
    dataIndex: 'directEquityNetValue',
    key: 'directEquityNetValue',
    align: 'right',
    ellipsis: true,
    width: 136,
    sortType: 'number',
    titleAlign: 'center',
  },
  {
    title: '日收益',
    dataIndex: 'directEquityIncome',
    key: 'directEquityIncome',
    align: 'right',
    ellipsis: true,
    width: 88,
    sortType: 'number',
    titleAlign: 'center',
  },
  {
    title: '日收益率(%)',
    dataIndex: 'directEquityYieldRate',
    key: 'directEquityYieldRate',
    align: 'right',
    ellipsis: true,
    width: 128,
    sortType: 'number',
    titleAlign: 'center',
  },
  {
    title: '净值',
    dataIndex: 'exceptStructFundNetValue',
    key: 'exceptStructFundNetValue',
    align: 'right',
    ellipsis: true,
    width: 312,
    sortType: 'number',
    titleAlign: 'center',
  },
  {
    title: '日收益',
    dataIndex: 'exceptStructFundIncome',
    key: 'exceptStructFundIncome',
    align: 'right',
    ellipsis: true,
    width: 88,
    sortType: 'number',
    titleAlign: 'center',
  },
  {
    title: '日率(%)',
    dataIndex: 'exceptStructFundYieldRate',
    key: 'exceptStructFundYieldRate',
    align: 'right',
    ellipsis: true,
    width: 128,
    sortType: 'number',
    titleAlign: 'center',
  },
  {
    title: '结值',
    dataIndex: 'structFundNetValue',
    key: 'structFundNetValue',
    align: 'right',
    ellipsis: true,
    width: 152,
    sortType: 'number',
    titleAlign: 'center',
  },
  {
    title: '日收益',
    dataIndex: 'structFundIncome',
    key: 'structFundIncome',
    align: 'right',
    ellipsis: true,
    width: 88,
    sortType: 'number',
    titleAlign: 'center',
  },
  {
    title: '日收益率(%)',
    dataIndex: 'structFundYieldRate',
    key: 'structFundYieldRate',
    align: 'right',
    ellipsis: true,
    width: 128,
    sortType: 'number',
    titleAlign: 'center',
  },
];
