import React, { Fragment, useState } from 'react';
import Table from '../index';

const columns = [
  {
    title: '一个比较长的标题',
    dataIndex: 'name',
    key: 'name',
    align: 'left',
    sortType: 'string',
    width: 200,
    ellipsis: true,
    fixed: 'left',
  },
  {
    title: '年龄',
    dataIndex: 'age',
    key: 'age',
    align: 'left',
    sortType: 'number',
    width: 226,
    ellipsis: true,
  },
  {
    title: '分数',
    dataIndex: 'score',
    key: 'score',
    align: 'left',
    sortType: 'number',
    width: 204,
    ellipsis: true,
  },
  {
    title: '分数1',
    dataIndex: '分数1',
    key: '分数1',
    align: 'left',
    sortType: 'number',
    width: 132,
  },
  {
    title: '分数12',
    dataIndex: '分数12',
    key: '分数12',
    align: 'left',
    sortType: 'number',
    width: 132,
  },
  {
    title: '分数123',
    dataIndex: '分数123',
    key: '分数123',
    align: 'left',
    sortType: 'number',
    fixed: 'right',
    width: 132,
  },
];

const columnsChange = [
  {
    title: '这是一个超长标题的demo超长超长超长超长',
    dataIndex: 'name',
    key: 'name',
    align: 'left',
    sortType: 'string',
    width: 100,
    ellipsis: false,
    fixed: 'left',
    sorter: () => {},
  },
  {
    title: '年龄',
    dataIndex: 'age',
    key: 'age',
    align: 'left',
    sortType: 'number',
    width: 100,
    ellipsis: false,
    fixed: 'left',
    sorter: () => {},
  },
  {
    title: '分数',
    dataIndex: 'score',
    key: 'score',
    align: 'left',
    sortType: 'number',
    width: 100,
    ellipsis: false,
    fixed: 'left',
    sorter: () => {},
  },
  {
    title: '测试标题',
    dataIndex: 'score1',
    key: 'score1',
    align: 'left',
    sortType: 'number',
    width: 100,
    sorter: () => {},
  },
  {
    title: '测试标题长一点长一点',
    dataIndex: 'name1',
    key: 'name1',
    align: 'left',
    sortType: 'string',
    width: 100,
    ellipsis: false,
    sorter: () => {},
  },
  {
    title: '年龄',
    dataIndex: 'age1',
    key: 'age1',
    align: 'left',
    sortType: 'number',
    width: 100,
    ellipsis: false,
    sorter: () => {},
  },
  {
    title: '分数',
    dataIndex: 'score2',
    key: 'score2',
    align: 'left',
    sortType: 'number',
    width: 100,
    ellipsis: false,
    sorter: () => {},
  },
  {
    title: '测试测试',
    dataIndex: 'score3',
    key: 'score3',
    align: 'left',
    sortType: 'number',
    fixed: 'right',
    width: 100,
    sorter: () => {},
  },
];

const data = [
  {
    name: 'Jack',
    age: 28,
    address: 'some where',
    name1: 'Jack',
    age1: 28,
    address1: 'some where',
    key: '1',
  },
  {
    name: 'Rose',
    age: 36,
    address: 'some where',
    name1: 'Rose',
    age1: 36,
    address1: 'some where',
    key: '2',
  },
  {
    name: 'Uzi',
    age: 36,
    address: 'some where',
    name1: 'Uzi',
    age1: 36,
    address1: 'some where',
    key: '3',
  },
  {
    name: 'ClearLove',
    age: 36,
    address: 'some where',
    name1: 'ClearLove',
    age1: 36,
    address1: 'some where',
    key: '4',
  },
  {
    name: 'Rookie',
    age: 36,
    address: 'some where',
    name1: 'Rookie',
    age1: 36,
    address1: 'some where',
    key: '5',
  },
  {
    name: 'TheShy',
    age: 36,
    address: 'some where',
    name1: 'TheShy',
    age1: 36,
    address1: 'some where',
    key: '6',
  },
  {
    name: 'TheShy',
    age: 36,
    address: 'some where',
    name1: 'TheShy',
    age1: 36,
    address1: 'some where',
    key: '6',
  },
  {
    name: 'TheShy',
    age: 36,
    address: 'some where',
    name1: 'TheShy',
    age1: 36,
    address1: 'some where',
    key: '6',
  },
  {
    name: 'TheShy',
    age: 36,
    address: 'some where',
    name1: 'TheShy',
    age1: 36,
    address1: 'some where',
    key: '6',
  },
  {
    name: 'TheShy',
    age: 36,
    address: 'some where',
    name1: 'TheShy',
    age1: 36,
    address1: 'some where',
    key: '6',
  },
  {
    name: 'TheShy',
    age: 36,
    address: 'some where',
    name1: 'TheShy',
    age1: 36,
    address1: 'some where',
    key: '6',
  },
  {
    name: 'TheShy',
    age: 36,
    address: 'some where',
    name1: 'TheShy',
    age1: 36,
    address1: 'some where',
    key: '6',
  },
  {
    name: 'TheShy',
    age: 36,
    address: 'some where',
    name1: 'TheShy',
    age1: 36,
    address1: 'some where',
    key: '6',
  },
  {
    name: 'TheShy',
    age: 36,
    address: 'some where',
    name1: 'TheShy',
    age1: 36,
    address1: 'some where',
    key: '6',
  },
  {
    name: 'TheShy',
    age: 36,
    address: 'some where',
    name1: 'TheShy',
    age1: 36,
    address1: 'some where',
    key: '6',
  },
];

const data2 = [
  {
    name: 'Jack1',
    age: 28,
    address: 'some where',
    name1: 'Jack',
    age1: 28,
    address1: 'some where',
    key: '1',
  },
  {
    name: 'Rose1',
    age: 36,
    address: 'some where',
    name1: 'Rose',
    age1: 36,
    address1: 'some where',
    key: '2',
  },
  {
    name: 'Uz1i',
    age: 36,
    address: 'some where',
    name1: 'Uzi',
    age1: 36,
    address1: 'some where',
    key: '3',
  },
  {
    name: 'Cl2earLove',
    age: 36,
    address: 'some where',
    name1: 'ClearLove',
    age1: 36,
    address1: 'some where',
    key: '4',
  },
  {
    name: 'Roo3kie',
    age: 36,
    address: 'some where',
    name1: 'Rookie',
    age1: 36,
    address1: 'some where',
    key: '5',
  },
  {
    name: 'The4Shy',
    age: 36,
    address: 'some where',
    name1: 'TheShy',
    age1: 36,
    address1: 'some where',
    key: '6',
  },
  {
    name: 'TheS5hy',
    age: 36,
    address: 'some where',
    name1: 'TheShy',
    age1: 36,
    address1: 'some where',
    key: '6',
  },
  {
    name: 'TheS6hy',
    age: 36,
    address: 'some where',
    name1: 'TheShy',
    age1: 36,
    address1: 'some where',
    key: '6',
  },
  {
    name: 'The6Shy',
    age: 36,
    address: 'some where',
    name1: 'TheShy',
    age1: 36,
    address1: 'some where',
    key: '6',
  },
  {
    name: 'TheS7hy',
    age: 36,
    address: 'some where',
    name1: 'TheShy',
    age1: 36,
    address1: 'some where',
    key: '6',
  },
  {
    name: 'TheS8hy',
    age: 36,
    address: 'some where',
    name1: 'TheShy',
    age1: 36,
    address1: 'some where',
    key: '6',
  },
];

export default () => {
  const [tableCol, setTableCol] = useState(columns);
  const [scrollX, setScrollX] = useState(1000);
  const [tableData, setTableData] = useState(data);
  const tihuan = () => {
    setScrollX(800);
    setTableCol(columnsChange);
    setTableData(data2);
  };

  return (
    <Fragment>
      <button onClick={tihuan}>替换表头</button>
      <div style={{ width: 600, height: 400 }}>
        <Table columns={tableCol} scroll={{ x: scrollX, y: 400 }} data={tableData} />
      </div>
    </Fragment>
  );
};
